### ISSUE TITLE
Python-validity and open-fprintd use old dependencies

### ISSUE THREAD

**Issue by osmo1** [ahbnr/nixos-06cb-009a-fingerprint-sensor#10]
Using `inputs.nixpkgs.follows = "nixpkgs";` when on 24.05 (and unstable). Results in the wrong python packages being downloaded for python-validity and open-fprintd.
An easy workaround was to just create an input of nixpkgs-23.11 and use that instead.

Python-validity: `python-validity-dbus-service[65321]: ImportError: cannot import name GLib, introspection typelib not found`
Open-fprintd: `open-fprintd[45222]: ImportError: cannot import name GObject, introspection typelib not found`

**Comment by adam-neeley** [comment]
I encountered the same error.

**Comment by nicklayb** [comment]
Same for me, I confirm that using 23.11 does fix it.

**Comment by ahbnr** [comment]
Hi!

I'm very sorry for reacting so late to the issues posted here.
I've had some time now to update the flake to work with NixOS 24.11. This should hopefully also work with NixOS Unstable for now.

Can you try out the following instructions and tell me if it works for you?
https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/blob/b3c609dc2069540cfcfc920d9dc0bd24f530a2bd/SETUP-24.11.md

Please note, that the configuration has changed a lot. 

Unfortunately, I am only using NixOS stable myself, so I will not keep the flake in sync with NixOS unstable.
